name: "publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "publish"
    runs-on: "ubuntu-latest"
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org

      - name: Installation
        run: npm install

      - name: Building
        run: npm run build

      - name: Testing
        run: npm run mocha

      - name: Publish to NPM
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_LEXXSOFT_TOKEN}}
